server:

  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true

  
logging:
  level:
    org.springframework: DEBUG
    com.mkyong: DEBUG

spring:
  profiles:
    active: dev
  main:
    banner-mode: off